spring:
  application:
    name: koalagrapher-api
  web:
    cors:
      mappings:
        "/galleries/**": #FIXME review this before release, remove allowed-origins
          allowed-origins: "http://localhost:3000"
          allowed-methods: "GET, POST, PUT, DELETE"
          allow-credentials: true

  servlet:
    multipart:
      max-file-size: 35MB
      max-request-size: 35MB
      enabled: true